[workspace]
members = [
    "math-archives",
    "backend-types",
    "search",
    "source/main/shared",
    "source/main/flams",
    "source/main/wasm",
    "source/utils",
    "source/database",
    "source/system",
    "source/web-utils",
    "source/lsp",
    "source/stex",
    "source/ftml/system",
    "source/git",
    "source/router/base",
    "source/router/dashboard",
    "source/router/content",
    "source/router/backend",
    "source/router/logging",
    "source/router/buildqueue/base",
    "source/router/buildqueue/components",
    "source/router/git/base",
    "source/router/git/components",
    "source/router/login",
    "source/router/search",
    "source/router/vscode-bindings",
    "source/router/flodown",
    #"experiments",
    "source/ffi", "solver/main","solver/trace"#,"solver/new"
    #"maintest"
, "source/buildsystem"]
    #"source/router/flodown",
    # "experiments",
    # "solver/new",
    #"maintest",
]
resolver = "2"
exclude = [
    "experiments",
    "target/rscript"
    #"web/graphs","test-plugin","tests","thaw",
    #"api", "controller", "core", "main", "ftml", "stex", "web/main", "web/orm"
]

# this is wasm, actually (because wasm-pack uses --release and --debug directly)
[profile.release]
strip = true
panic = 'abort'
opt-level = 'z'
lto = true

# this is wasm, actually (because wasm-pack uses --release and --debug directly)
[profile.dev]
panic = 'abort'
opt-level = 'z'
lto = true
debug=true

[profile.flams-release]
inherits = "release"
opt-level = 2
lto = "fat" # "thin" #
codegen-units = 1
panic = "unwind"


[profile.flams-dev]
inherits = "dev"
opt-level = 0

#[profile.dev.package."*"]
#opt-level=3

[profile.bench]
strip = "none"

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits = "release"

[profile.wasm-dev]
inherits = "dev"
panic = 'unwind'

[workspace.metadata.wasm-pack.profile.dev.wasm-bindgen]
debug-js-glue = true
demangle-name-section = true
dwarf-debug-info = true

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "--cfg",
    "docsrs",
    "--html-in-header",
    "resources/katex-header.html",
    "--html-in-header",
    "resources/flams-docs.html",
    "--enable-index-page",
    "-Zunstable-options",
    "--generate-link-to-definition",
]

[workspace.lints.rust]
#unsafe_code = "deny"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = 1 }
nursery = { level = "warn", priority = 2 }
unwrap_used = "warn"
module_name_repetitions = { level = "allow", priority = 0 }
enum_glob_use = { level = "allow", priority = 0 }
redundant_else = { level = "warn", priority = 1 }
similar_names = { level = "warn", priority = 1 }
too_many_lines = { level = "warn", priority = 1 }

[workspace.dependencies]
# flams
flams-ftml = { path = "source/ftml/system" }
flams-stex = { path = "source/stex" }
flams-utils = { path = "source/utils" }
flams-system = { path = "source/system" }
flams-database = { path = "source/database" }
flams-lsp = { path = "source/lsp" }
flams-git = { path = "source/git" }
flams-web-utils = { path = "source/web-utils" }
ftml-solver = { path = "solver/main" }
ftml-solver-trace = { path = "solver/trace" }

flams-main = { path = "source/main/shared" }

flams-router-base = { path = "source/router/base" }
flams-router-dashboard = { path = "source/router/dashboard" }
flams-router-content = { path = "source/router/content" }
flams-router-backend = { path = "source/router/backend" }
flams-router-buildqueue-base = { path = "source/router/buildqueue/base" }
flams-router-buildqueue-components = { path = "source/router/buildqueue/components" }
flams-router-git-base = { path = "source/router/git/base" }
flams-router-git-components = { path = "source/router/git/components" }
flams-router-login = { path = "source/router/login" }
flams-router-logging = { path = "source/router/logging" }
flams-router-search = { path = "source/router/search" }
flams-router-vscode = { path = "source/router/vscode-bindings" }
#flams-flodown = { path = "source/router/flodown" }

# refactor
flams-math-archives = { path = "math-archives" }
flams-backend-types = { path = "backend-types" }
flams-search = { path = "search" }

# FTML
ftml-uris = { git = "https://github.com/FlexiFormal/FTML", features = ["interned"] }
ftml-ontology = { git = "https://github.com/FlexiFormal/FTML" }
ftml-backend = { git = "https://github.com/FlexiFormal/FTML" }
ftml-parser = { git = "https://github.com/FlexiFormal/FTML" }
ftml-components = { git = "https://github.com/FlexiFormal/FTML" }
ftml5ever = { git = "https://github.com/FlexiFormal/FTML" }
ulo = { git = "https://github.com/FlexiFormal/FTML" }
ftml-dom = { git = "https://github.com/FlexiFormal/FTML" }
ftml-component-utils = { git = "https://github.com/FlexiFormal/FTML" }

#flodown = { git = "https://github.com/FlexiFormal/FloDown" }

#ftml-uris = { path = "../FTML/uris", features = ["interned"] }
#ftml-ontology = { path = "../FTML/ontology" }
#ftml-backend = { path = "../FTML/backend" }
#ftml-parser = { path = "../FTML/parser" }
#ftml-components = { path = "../FTML/components" }
#ftml5ever = { path = "../FTML/ftml5ever" }
#ulo = { path = "../FTML/ulo" }
#ftml-dom = { path = "../FTML/dom" }
#ftml-component-utils = {path = "../FTML/component-utils"}

#flodown = { path="../FloDown/flodown" }

rustex_lib = { version = "0.1", features = ["multithreaded"] }
tex_engine = { version = "0.1", features = ["multithreaded"] }
#rustex_lib = { path = "../RusTeX/rustex", features = ["multithreaded"] }
#tex_engine = { path = "../RusTeX/tex_engine", features = ["multithreaded"] }

dateparser = "0.3.1"#{git = "https://github.com/Jazzpirate/dateparser"}

rstest = { version = "0.26" }

# utils

utoipa-swagger-ui = {version="9",features=["vendored","axum"]}
utoipa = "5"
utoipa-axum = "0.2"

orx-parallel = "3"
document-features = "0.2"
rustc_version = "0.4"
const-str = "1"
triomphe = "0.1"
parking_lot = "0.12"
serde-wasm-bindgen = "0.6"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = { version = "1", features = ["unbounded_depth"] }
serde_stacker = "0.1"
rustc-hash = "2"
chrono = "0.4"
oxrdf = "0.3"
smallvec = { version = "2.0.0-alpha.12" }
lazy_static = "1.5"
url = "2"
either = "1"
either_of = "0.1"
const_format = "0.2"
paste = "1"
urlencoding = "2.1"
send_wrapper = "0.6.0"
inventory = "0.3"
rayon = "1.10"
spliter = "0.1"
walkdir = "2.5"
filetime = "0.2"
regex = "1.10"
fancy-regex = "0.19"
async-broadcast = "0.7"
simple-home-dir = "0.5"
async-trait = "0.1"
bytesize = "2"
deepsize = "0.2"
bincode = { version = "2", features = ["derive", "serde"] }
postcard = { version = "1.1", features = ["use-std"] }
lightningcss = { version = "1.0.0-alpha.63", default-features = false }
# cfg-if = "1"
tokio = { version = "1" }                                                   #, features = ["fs","io-util","sync","test-util","macros","rt"] }
tokio-util = { version = "0.7", features = ["compat"] }
tokio-stream = { version = "0.1" }
tempfile = { version = "3" }
phf = { version = "0.14", default-features = false, features = ["macros"] }
crossbeam-channel = { version = "0.5" }
flate2 = { version = "1.0" }
tar = { version = "0.4" }
async-compression = { version = "0.4", features = ["tokio", "gzip"] }
astral-tokio-tar = "0.5.1"
strum = { version = "0.28", features = ["derive"] }
git-url-parse = { version = "0.4" }
flume = { version = "0.12", features = ["async"] }
ordered-float = "5"

password-hash = { version = "0.5" }
argon2 = { version = "0.5" }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "smallvec",
    "parking_lot",
    "json",
] }
# tracing-appender = "0.2"
tracing-error = "0.2"

toml = "1"
serde_yml = "0.0.12"
serde-value = "0.7"
eyre = "0.6"
color-eyre = "0.6"
thiserror = "2"
clap = { version = "4.5", features = ["derive"] }

oxigraph = { version = "0.5", default-features = false, features=["rdf-12"] }
oxiri = "0.2" # oxigraph needs this (currently)
spargebra = "0.4"
sparesults = {version="0.3",features=["sparql-12"]}
oxrdfio = { version = "0.2" }                            #, features = ["async-tokio"] }

sqlx = { version = "0.9", features = ["sqlite", "macros", "runtime-tokio"] }
libsqlite3-sys = { version = "*", features = ["bundled"] }
html5ever = "0.39"                                                           # TODO update once html2text updates markup5ever dependency

async-lsp = { version = "0.2", features = ["tokio", "async-io"] }
futures = { version = "0.3" }
oauth2 = { version = "5" }

reqwest = { version = "0", features = ["json"] }

image = { version = "0.25" }
#webp = { version = "0.3" }
dashmap = { version = "6" }

gitlab = { version = "0" }
git2 = { version = "0.20", features = ["vendored-libgit2", "vendored-openssl"] }


# leptos
leptos = "0.8"#{ version = "=0.8.14"}#, features = ["nightly"] }
leptos_axum = "0.8"
leptos_meta = "0.8"
leptos_router = { version = "0.8"}#, features = ["nightly"] }
# leptos_use = {version="0.15", default-features = false}

leptos-posthoc = "0.2" #{ version = "0.2", git = "https://github.com/FlexiFormal/leptos-posthoc.git" }
#leptos-posthoc = { path = "../leptos_dyn_dom" }

bytes = "1.10"
icondata_bi = "0"

axum = { version = "0.8", features = ["ws"] }
axum-macros = { version = "0.5" }
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.7", features = ["fs", "trace", "cors"] }
tower-sessions = { version = "0.14" } # version required by axum-login :-/
axum-login = { version = "0.18" }
http = { version = "1" }
mime_guess = "2"

# wasm
wasm-bindgen = "0.2.121"
js-sys = "0.3"

tracing-wasm = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1.7"
#reqwasm = "0.5"
gloo-storage = "0.4"
gloo-timers = "0.4"
web-sys = { version = "0.3" }
#tsify-next = { version = "0.5", features = ["js"] }
tsify = { version = "0.5", features = ["js"] }
js-regexp = "0.2"
wasm-streams = "0.5" #something reqwest requires <0.6
futures-util = "0.3"

# search

#html2text = "0.15"
tantivy = "0.26"
simsimd = "6"
fastembed = "6"
#ort-candle = "0.2.0+0.9"
ort = { version="2.0.0-rc.11"}#, default-features = false, features = ["alternative-backend"] }

waken_snowball = "0.1"
radix_trie = "0.3"
memchr = "2.7"
arrayvec = "0.7"

ahash = "0.8"
getrandom = "0.3" # version required by ahash :-/

#[patch.crates-io]
#thaw = { git = 'https://github.com/thaw-ui/thaw' }
#thaw_utils = { git = 'https://github.com/thaw-ui/thaw' }
#thaw_components = { git = 'https://github.com/thaw-ui/thaw' }


[replace]
"serde-lite:0.5.1" = { git = 'https://github.com/Jazzpirate/serde-lite',branch="hashmaps" }

[[workspace.metadata.leptos]]
hash-files = true
hash-file-name = "hash.txt"
name = "flams"
#output-name = "flams"
bin-package = "flams"
lib-package = "flams-wasm"
bin-features = ["tantivy"] #,"vectorsearch"] #
lib-features = [] #["hydrate"]
lib-default-features = false
bin-profile-release = "flams-release"
bin-profile-dev = "flams-dev"
lib-profile-release = "wasm-release"
lib-profile-dev = "wasm-dev"
bin-default-features = false
site-root = "target/web"
assets-dir = "resources/assets"
site-pkg-dir = "pkg"
style-file = "resources/main.scss"
browserquery = "defaults"
lib-cargo-args = [
    "--target",
    "wasm32-unknown-unknown",
    #"-Z",
    #"build-std=std,panic_abort,core,alloc",
    #"-Z",
    #"build-std-features=optimize_for_size",
    "--timings",
]
bin-cargo-args = ["--timings"]

# dafuq:
# https://higherorderco.com/
# https://github.com/HigherOrderCO/kind
# https://cse.sc.edu/~pfu/document/papers/rta-tlca.pdf


## https://www.arroyo.dev/blog/rust-plugins


# utils:
# https://docs.rs/inventory/latest/inventory/ <- cross-project collecting of things
# https://crates.io/crates/lol_html <- HTML parsing/rewriting
# https://docs.rs/memchr/2.7.4/memchr/ <- fast string search
# https://docs.rs/icondata/latest/icondata/ <- icons
# https://crates.io/crates/flume channels?

# search:
# https://docs.rs/crate/tantivy/latest

#dbs:
# https://github.com/async-graphql/async-graphql?tab=readme-ov-file
# https://github.com/surrealdb/surrealdb/pull/3797
# https://github.com/graphql-rust/juniper
# https://docs.rs/tokio-rusqlite
# https://bonsaidb.io/

# interesting: https://github.com/rodrimati1992/abi_stable_crates

# https://nullderef.com/series/rust-plugins/
# https://github.com/marioortizmanero/pdk-experiments/tree/master/abi-stable-connectors

# https://fasterthanli.me/articles/so-you-want-to-live-reload-rust
# https://www.michaelfbryan.com/rust-ffi-guide/dynamic_loading.html
# https://zicklag.github.io/rust-tutorials/rust-plugins.html

# cglue?
# https://github.com/h33p/cglue/tree/main/examples

# https://crisal.io/words/2020/02/28/C++-rust-ffi-patterns-1-complex-data-structures.html


# prolly not:
# https://gitlab.com/zack-emmert/abi_trait
