[package]
name = "flams-math-archives"
version = "0.0.1"
edition = "2024"

[lib]
crate-type = ["rlib"]

[lints]
workspace = true

[features]
## Uses rocksdb storage for the triple store rather than in-memory
# rocksdb = ["rdf","oxigraph/rocksdb","oxigraph/oxrocksdb-sys"]
## Enables RDF support
rdf = [
    "ftml-ontology/rdf",
    "ftml-uris/rdf",
    "flams-backend-types/rdf",
    "dep:ulo",
    "dep:oxigraph",
    "dep:spargebra",
    "dep:sparesults",
    "dep:oxiri"
]
## adds memory "monitoring"
deepsize = ["dep:deepsize", "dep:bytesize", "ftml-ontology/deepsize"]
## adds git suppert for math archives that are git repos
git = ["dep:flams-git", "dep:url"]
## caches documents and modules in global backend
cached = []
## resolving image urls/uris and conversion to webp, also html-standalone-export
img = ["dep:tex_engine","dep:image","dep:fancy-regex"]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "--cfg",
    "docsrs",
    "-Zunstable-options",
    "--generate-link-to-definition",
    "--html-in-header",
    "doc/katex-header.html",
    "--html-in-header",
    "doc/docs.html",
]
# cargo +nightly doc --no-deps --all-features --release --open

[build-dependencies]
rustc_version = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
#rstest = { workspace = true }
#criterion = { workspace = true }

[dependencies]
document-features = { workspace = true }

ftml-ontology = { workspace = true }
ftml-backend = { workspace = true, features=["cached"] }
ftml-uris = { workspace = true, features = ["interned"] }
flams-backend-types = { workspace = true, features = ["serde"] }
flams-git = { workspace = true, optional = true, features = ["git2"] }

inventory = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
smallvec = { workspace = true }
tracing = { workspace = true }
simple-home-dir = { workspace = true }
filetime = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
parking_lot = { workspace = true }
either = { workspace = true }
walkdir = { workspace = true }
const_format = { workspace = true }
#postcard = { workspace = true }
bincode = { workspace = true, features = ["std", "serde"] }
triomphe = { workspace = true }
dashmap = { workspace = true }
rustc-hash = { workspace = true }
#flume = { workspace = true }
futures-util = { workspace = true }

# orx-parallel = { workspace = true }
# # This is faster:
spliter = { workspace = true }
rayon = { workspace = true }

ulo = { workspace = true, optional = true }
tsify = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
oxigraph = { workspace = true, optional = true }
oxiri = { workspace = true, optional = true }
spargebra = { workspace = true, optional = true }
sparesults = { workspace = true, optional = true }
deepsize = { workspace = true, optional = true }
bytesize = { workspace = true, optional = true }
url = { workspace = true, optional = true }
tex_engine = {workspace = true, optional = true}
image = {workspace = true, optional = true}
fancy-regex = {workspace = true,optional = true}
