[package]
name = "flams-main"
version = "0.0.6"
edition = "2024"
description = "𝖥𝖫∀𝖬∫ - Flexiformal Annotation Management System"

[lib]
name = "flams_main"
crate-type = ["rlib"]

#[package.metadata.wasm-pack.profile.release]
#wasm-opt = ['-Oz','--enable-bulk-memory','--all-features']

#[package.metadata.wasm-pack.profile.dev]
#wasm-opt = false

[features]
docs = []
ssr = [
    "ftml-uris/leptos",
    "dep:flams-search",
    "dep:flams-system",
    "dep:flams-stex",
    "dep:flams-ftml",
    "dep:flams-math-archives",
    "dep:tokio",
    "dep:color-eyre",
    "dep:sqlx",
    "dep:libsqlite3-sys",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "dep:leptos_axum",
    "ftml-component-utils/ssr",
    "dep:axum",
    "dep:axum-macros",
    "dep:tower",
    "dep:tower-http",
    "dep:tower-sessions",
    "dep:axum-login",
    "dep:async-trait",
    "dep:password-hash",
    "dep:argon2",
    "dep:http",
    "flams-web-utils/ssr",
    "ftml-components/ssr",
    "dep:flams-lsp",
    "dep:tokio-util",
    "dep:rayon",
    "dep:tex_engine",
    "dep:image",
    #"dep:webp",
    "dep:dashmap",
    "dep:futures",
    "dep:mime_guess",
    "flams-database/backend",
    "flams-git/gitlab",
    "flams-git/git2",
    "flams-router-dashboard/ssr",
    "flams-router-base/ssr",
]
hydrate = [
    "dep:console_error_panic_hook",
    "leptos/hydrate",
    "ftml-component-utils/hydrate",
    "dep:wasm-bindgen",
    "tracing/release_max_level_warn",
    "dep:tracing-wasm",
    "flams-web-utils/hydrate",
    "leptos-posthoc/hydrate",
    "ftml-components/hydrate",
    "flams-router-dashboard/hydrate",
    "flams-router-base/hydrate",
    "ftml-ontology/wasm",
    "dep:dateparser",
    #"getrandom/wasm_js"
]
tantivy = [
    "flams-search/tantivy",
    "flams-system/tantivy",
]
vectorsearch = [
    "flams-search/vectorsearch",
    "flams-router-search/vectorsearch",
    "flams-system/vectorsearch",
    "flams-router-dashboard/vectorsearch"
]

[dev-dependencies]
#rstest = "0.21"
#tracing-subscriber = "0.3"

[lints]
workspace = true

[dependencies]
ftml-uris = { workspace = true }
ftml-ontology = { workspace = true, features = ["serde"] }
ftml-components = { workspace = true }

ftml-component-utils = {workspace = true}

flams-router-dashboard = { workspace = true }
flams-router-content = {workspace = true}
flams-backend-types = { workspace = true }
flams-router-search = { workspace = true }
flams-router-base = { workspace = true }
flams-web-utils = { workspace = true }
flams-utils = { workspace = true, features = ["serde"] }
#flams-ontology = { workspace = true, features = ["serde"] }
#ftml-viewer-components = { workspace = true, features = ["omdoc"] }
flams-git = { workspace = true }
flams-system = { workspace = true, features = [
    "zip",
    "gitlab",
    #"rocksdb"
], optional = true }
flams-search = { workspace = true, optional = true }
flams-math-archives = { workspace = true, optional = true,features=["deepsize","cached","img"] }
flams-lsp = { workspace = true, optional = true, features = ["ws"] }
flams-stex = { workspace = true, optional = true }
flams-ftml = { workspace = true, optional = true }
flams-database = { workspace = true }

# common
leptos = { workspace = true }
leptos_meta = { workspace = true }
leptos_router = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
either = { workspace = true }
const-str = { workspace = true }
leptos-posthoc = { workspace = true }
paste = { workspace = true }
lazy_static = { workspace = true }
urlencoding = { workspace = true }
smallvec = { workspace = true }

# ssr
tex_engine = { workspace = true, optional = true }
mime_guess = { workspace = true, optional = true }

tokio = { workspace = true, features = [
    "full","io-uring","parking_lot"
], optional = true }
color-eyre = { workspace = true, optional = true }
leptos_axum = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }

sqlx = { workspace = true, optional = true }
libsqlite3-sys = { workspace = true, optional = true }

axum = { workspace = true, optional = true,features=["macros"] }           #,features=["macros"]}
axum-macros = { workspace = true, optional = true }
tower = { workspace = true, optional = true }
tower-http = { workspace = true, optional = true }
tower-sessions = { workspace = true, optional = true }
axum-login = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }
http = { workspace = true, optional = true }
futures = { workspace = true, optional = true }

password-hash = { workspace = true, optional = true }
argon2 = { workspace = true, optional = true }

tokio-util = { workspace = true, optional = true }

image = { workspace = true, optional = true }
#webp = { workspace = true, optional = true }
dashmap = { workspace = true, optional = true }

#hydrate
console_error_panic_hook = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
tracing-wasm = { workspace = true, optional = true }
dateparser = {workspace = true,optional = true,features=["wasm"]}

#ahash = { workspace = true }
#getrandom = {workspace=true}

#tachys = {workspace = true}
#server_fn = {workspace = true}
#leptos_macro = {workspace = true}
#server_fn_macro = {workspace = true}
#server_fn_macro_default = {workspace = true}
#leptos_router_macro = {workspace = true}
#leptos_config = {workspace = true}
#leptos_dom = {workspace = true}

#reactive_graph = {workspace = true}
#hydration_context = {workspace = true}
