[package]
name = "flams-search"
version = "0.0.1"
edition = "2024"

[lib]
crate-type = ["rlib"]

[lints]
workspace = true

[features]
tantivy = ["dep:tantivy","ftml-uris/tantivy","flams-backend-types/bincode"]
vectorsearch = ["dep:fastembed","dep:ort","flams-backend-types/vectorsearch"]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "--cfg",
    "docsrs",
    "-Zunstable-options",
    "--generate-link-to-definition",
    "--html-in-header",
    "doc/katex-header.html",
    "--html-in-header",
    "doc/docs.html",
]
# cargo +nightly doc --no-deps --all-features --release --open

[build-dependencies]
rustc_version = { workspace = true }

[dev-dependencies]
#tracing-subscriber = { workspace = true }
#rstest = { workspace = true }
#criterion = { workspace = true }

[dependencies]
document-features = { workspace = true }

flams-system = { workspace = true }
flams-backend-types = { workspace = true }
flams-math-archives = { workspace = true, features = ["rdf"] }

ftml-uris = { workspace = true }
ftml-ontology = { workspace = true }
ftml-parser = { workspace = true }

bincode = { workspace = true }
serde = { workspace = true }
either = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
#html2text = { workspace = true }
rayon = { workspace = true }
walkdir = { workspace = true }
ordered-float = { workspace = true }

html5ever = { workspace = true }

tantivy = { workspace = true,optional=true }
fastembed = { workspace = true,optional=true }
ort = { workspace = true,optional=true }
#ort-candle = { workspace = true,optional=true }
