# debug = false
# log_dir = "~/.flams/log"
# temp_dir = "~/.flams/tmp"
# embedding_dir = "~/.flams/embedding"
# database = "~/.flams/users.sqlite"
# rdf_database = "~/.flams/rdf"
# stack_size = 2

[server]
# port = 8095
# ip = "127.0.0.1"
# admin_pwd = "foobar"
# external_url = "https://mathhub.info"

[buildqueue]
# num_threads=6

[gitlab]
# url = "https://mathhub.info"
# token = "SECRET_TOKEN"
# app_id = "APP_ID"
# app_secret = "APP_SECRET"
# redirect_url = "http://localhost:3000"

[remotes]
mathhub = "https://mathhub.info"
