[package]
name = "flams-lsp"
version = "0.0.1"
edition = "2024"

[lints]
workspace = true

[features]
ws = ["dep:axum"]

[dependencies]
ftml-ontology = { workspace = true }
ftml-uris = { workspace = true, features = ["interned", "serde"] }

flams-math-archives = { workspace = true,features=["rdf","img"] }

flams-system = { workspace = true, features = ["tokio", "zip"] }
flams-ftml = { workspace = true }
flams-utils = { workspace = true }
flams-stex = { workspace = true }
ftml-solver = {workspace = true}

rustc-hash = { workspace = true }
#dashmap.workspace = true
tracing = { workspace = true }
async-lsp = { workspace = true }
futures = { workspace = true }
tower = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
triomphe = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
eyre = { workspace = true }
serde_json = { workspace = true }
either_of = { workspace = true }

axum = { workspace = true, optional = true }
lazy_static = { workspace = true }
smallvec = { workspace = true }

waken_snowball.workspace = true
radix_trie.workspace = true
