[package]
name = "buildsystem"
version = "0.1.0"
edition = "2024"

[dependencies]
petgraph = "0.8.3"
tracing.workspace = true
tracing-subscriber.workspace = true
tokio = { workspace = true, features = ["sync", "rt"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }

[lints]
workspace = true
